services:
    sn_deploy.twig:
        class: SN\DeployBundle\Services\Version
        arguments: ['%kernel.root_dir%']
        lazy: true
    sn_deploy.request_collector:
        class: SN\DeployBundle\DataCollector\RequestCollector
        arguments: ['%sn_deploy%', '%kernel.root_dir%']
        public: false
        tags:
            - { name: data_collector, template: '@SNDeploy/webprofiler.html.twig', id: 'sn_deploy.request_collector' }
